---
 
- name: Install Krombox
  hosts: all
  remote_user: mattiss
  become: false
  become_method: sudo

  vars:
    - user_bin_directory: "{{ ansible_env.HOME }}/bin"
    - additional_hosts:
      - name: bananas
        ip: 192.168.1.19
    - nas_server: bananas

  pre_tasks:
    - name: "Build hosts file"
      lineinfile: dest=/etc/hosts 
                state=present
                dest=/etc/hosts 
                regexp='.*{{ item.name }}$' line="{{ item.ip }} {{item.name}}" 
      with_items: "{{ additional_hosts }}"  
      become: true
  
  roles:
    - role: autofs
      become: yes
      autofs_indirect_maps:
        - name: auto.{{ nas_server }}
          path: /mnt/{{ nas_server }}
          mounts:
            - name: "*"
              options: "-vers=3"
              url: "{{ nas_server }}:/volume1/&"	
    - role: kodi
      kodi_source_music: [ '/mnt/{{ nas_server }}/music' ]
      kodi_source_videos: [ '/mnt/{{ nas_server }}/video/movies', '/mnt/{{ nas_server }}/video/flims', '/mnt/{{ nas_server }}/kids', '/mnt/{{ nas_server }}/downloads' ]      
    - molotov.tv
<<<<<<< HEAD
    # - caffeine
=======
>>>>>>> 52f2558a247f926f8ab979a19d756cecfec5f32d
    - role: acestreamplayer
    - role: powershell
    - role: vscode
      tags: 'test'
<<<<<<< HEAD
    - role: vpn
=======
    - role: docker
      vars:
        - remote_user: mattiss
      tags: 'docker'
>>>>>>> 52f2558a247f926f8ab979a19d756cecfec5f32d
    # - dolphin	
    # - steam

  # tasks:
    # Fetches the docker installation script
    # from `get.docker.com` and then pipes the
    # script to `sh` so that it gets executed.
    # - name: 'install docker'
    #   command: 'bash -c "curl -fsSL https://get.docker.com/ | sh"'
      