---
 
- name: Install HTPC
  hosts: sandbox
  remote_user: mattiss
  become: false
  become_method: sudo

  vars:
    user_bin_directory: "{{ ansible_env.HOME }}/bin"
  
  roles:
    - role: autofs
      sudo: yes
      autofs_indirect_maps:
        - name: auto.bananas
          path: /mnt/bananas
          mounts:
            - name: "*"
              url: "bananas:/volume1/&"	  
    - powershell
    - vpn
    - molotov.tv
    - kodi	
    - dolphin	
    - steam
    - caffeine