---
 
- name: Install HTPC
  hosts: sandbox
  remote_user: mattiss
  become: false
  become_method: sudo

  vars:
    user_bin_directory: "{{ ansible_env.HOME }}/bin"
  
  roles:
    - caffeine
    - autofs
    - vpn
    - molotov.tv
    - powershell
    - kodi	
    - dolphin	
    - steam
