---

# ----- Setup -----
- name: "Make sure snap package manager is installed"
  apt: name="{{ item }}" update_cache=yes
  with_items: "{{ snap_pkgs }}"
  become: true
  environment:
    PATH: $PATH:/SNAP/node/bin

- name: "Deploy vscode snap"
  command: snap install {{ vscode_snap }}
  become: true