---

- name: "Ensure kodi repository is present"
#  apt_repository: repo="{{ item }}"
  add_ppa: name="{{ item }}"
  with_items: "{{ kodi_repository }}"
  become: true
  
- name: "Ensure kodi package(s) present"
  apt: name="{{ item }}" update_cache=yes state=latest
  with_items: "{{ kodi_pkgs }}"
  become: true

- name: "Ensure config folders exist"
  file: path={{ item }} state=directory 
  with_items:
    - "{{ kodi_conf_dir }}"
    - "{{ kodi_conf_dir }}/userdata"

- name: "Config sources.xml"
  template: src=sources.xml.j2 dest="{{ kodi_conf_dir }}/userdata/sources.xml" 
  
- name: "Config advancedsettings.xml"
  template: src=advancedsettings.xml.j2 dest="{{ kodi_conf_dir }}/userdata/advancedsettings.xml" 
